codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 85%
        threshold: 2%
    changes:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

# Critical path files require 100% coverage
flag_management:
  individual_flags:
    - name: critical-paths
      paths:
        - src/utils/optionUtils.js
      carryforward: false
      statuses:
        - type: project
          target: 100%
          threshold: 0%

ignore:
  - "tests/**/*"
  - "examples/**/*"
  - "checkops-power/examples/**/*"
  - "migrations/**/*"
  - "docs/**/*"
