# CodeRabbit AI Review Configuration
# https://docs.coderabbit.ai/reference/configuration

# Language for reviews
language: en-US

# Enable early access features
early_access: true

# Reviews configuration
reviews:
  # Auto-review settings
  auto_review:
    enabled: true
    drafts: false  # Ignore draft PRs
  
  # High-level summary
  high_level_summary: false
  
  # Path-based exclusions (use path_instructions with ignore)
  path_instructions:
    - path: "node_modules/**"
      instructions: "Ignore this path"
    
    - path: "package-lock.json"
      instructions: "Ignore this file"
    
    - path: "*.log"
      instructions: "Ignore log files"
    
    - path: "coverage/**"
      instructions: "Ignore coverage reports"
    
    - path: "dist/**"
      instructions: "Ignore build artifacts"
    
    - path: "build/**"
      instructions: "Ignore build artifacts"
    
    - path: "**/*.js"
      instructions: |
        Focus on:
        - SQL injection prevention in database queries
        - Proper error handling and logging
        - Input validation and sanitization
        - Security best practices for MCP server implementation
        - Performance optimization
    
    - path: "**/*.sql"
      instructions: |
        Ensure:
        - Migrations are safe and reversible
        - No SQL injection vulnerabilities
        - Proper indexing considerations
        - Data integrity constraints
    
    - path: "**/src/**/*.js"
      instructions: |
        Review for:
        - Proper async/await usage
        - Error boundary implementation
        - Memory leak prevention
        - Security vulnerabilities
  
  # Tools configuration
  tools:
    eslint:
      enabled: true

# Knowledge base configuration
knowledge_base:
  code_guidelines:
    filePatterns:
      - "docs/**/*.md"
      - "README.md"
      - "CONTRIBUTING.md"

# Chat configuration
chat:
  auto_reply: false