/**
 * Form Model - v4.0.0
 * 
 * This model uses the dual-ID system:
 * - id (UUID): Internal primary key for all database operations
 * - sid (VARCHAR): Human-readable ID (FORM-001) for display only
 */

import { getPool } from '../config/database.js';
import { generateSID, getNextSIDCounter } from '../utils/idResolver.js';
import { DatabaseError, NotFoundError } from '../utils/errors.js';

export class Form {
    constructor(data) {
        this.id = data.id;                                    // UUID (primary key)
        this.sid = data.sid;                                  // Human-readable (FORM-001)
        this.title = data.title;
        this.description = data.description;
        this.questions = data.questions;
        this.metadata = data.metadata;
        this.requireAll = data.require_all ?? data.requireAll ?? true;
        this.isActive = data.isActive ?? data.is_active;
        this.createdAt = data.createdAt ?? data.created_at;
        this.updatedAt = data.updatedAt ?? data.updated_at;
    }

    toJSON() {
        return {
            id: this.id,           // UUID for API operations
            sid: this.sid,         // Human-readable for display
            title: this.title,
            description: this.description,
            questions: this.questions,
            metadata: this.metadata,
            requireAll: this.requireAll,
            isActive: this.isActive,
            createdAt: this.createdAt,
            updatedAt: this.updatedAt,
        };
    }

    static fromRow(row) {
        if (!row) return null;
        return new Form({
            id: row.id,
            sid: row.sid,
            title: row.title,
            description: row.description,
            questions: row.questions,
            metadata: row.metadata,
            requireAll: row.require_all,
            isActive: row.is_active,
            createdAt: row.created_at,
            updatedAt: row.updated_at,
        });
    }

    static async create({ title, description, questions, metadata = {}, requireAll = true }) {
        const pool = getPool();

        // Generate SID (human-readable ID)
        const counter = await getNextSIDCounter('form');
        const sid = generateSID('form', counter);

        // Build enhanced metadata
        const enhancedMetadata = Form.buildEnhancedMetadata(questions, metadata);

        try {
            // UUID is generated by database (DEFAULT gen_random_uuid())
            const result = await pool.query(
                `INSERT INTO forms (sid, title, description, questions, metadata, require_all, is_active)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         RETURNING *`,
                [sid, title, description, JSON.stringify(questions), JSON.stringify(enhancedMetadata), requireAll, true]
            );

            return Form.fromRow(result.rows[0]);
        } catch (error) {
            throw new DatabaseError('Failed to create form', error);
        }
    }

    static buildEnhancedMetadata(questions, metadata = {}) {
        // Return only user-provided metadata
        // No internal clutter (_version, _createdAt, _questionBankMapping)
        return metadata;
    }

    /**
     * Find form by UUID (internal use)
     * @param {string} uuid - UUID only
     * @returns {Promise<Form>}
     */
    static async findById(uuid) {
        const pool = getPool();

        const result = await pool.query('SELECT * FROM forms WHERE id = $1', [uuid]);

        if (result.rows.length === 0) {
            throw new NotFoundError('Form', uuid);
        }

        return Form.fromRow(result.rows[0]);
    }

    /**
     * Find form by SID (user-facing)
     * @param {string} sid - SID only (e.g., 'FORM-001')
     * @returns {Promise<Form>}
     */
    static async findAll({ isActive = null, limit = 100, offset = 0 } = {}) {
        const pool = getPool();
        let query = 'SELECT * FROM forms';
        const params = [];

        if (isActive !== null) {
            query += ' WHERE is_active = $1';
            params.push(isActive);
        }

        query += ` ORDER BY created_at DESC LIMIT $${params.length + 1} OFFSET $${params.length + 2}`;
        params.push(limit, offset);

        const result = await pool.query(query, params);
        return result.rows.map((row) => Form.fromRow(row));
    }

    /**
     * Update form by UUID (internal use)
     * @param {string} uuid - UUID only
     * @param {object} updates - Fields to update
     * @returns {Promise<Form>}
     */
    static async updateById(uuid, updates) {
        const pool = getPool();

        // First verify the form exists
        const form = await Form.findById(uuid);

        const setClauses = [];
        const values = [];
        let paramIndex = 1;

        if (updates.title !== undefined) {
            setClauses.push(`title = $${paramIndex++}`);
            values.push(updates.title);
        }

        if (updates.description !== undefined) {
            setClauses.push(`description = $${paramIndex++}`);
            values.push(updates.description);
        }

        if (updates.questions !== undefined) {
            setClauses.push(`questions = $${paramIndex++}`);
            values.push(JSON.stringify(updates.questions));
        }

        if (updates.metadata !== undefined) {
            setClauses.push(`metadata = $${paramIndex++}`);
            values.push(JSON.stringify(updates.metadata));
        }

        if (updates.requireAll !== undefined) {
            setClauses.push(`require_all = $${paramIndex++}`);
            values.push(updates.requireAll);
        }

        if (updates.isActive !== undefined) {
            setClauses.push(`is_active = $${paramIndex++}`);
            values.push(updates.isActive);
        }

        if (setClauses.length === 0) {
            return form;
        }

        values.push(uuid);
        const query = `UPDATE forms SET ${setClauses.join(', ')} WHERE id = $${paramIndex} RETURNING *`;

        try {
            const result = await pool.query(query, values);
            return Form.fromRow(result.rows[0]);
        } catch (error) {
            throw new DatabaseError('Failed to update form', error);
        }
    }

    /**
     * Update form by SID (user-facing)
     * @param {string} sid - SID only (e.g., 'FORM-001')
     * @param {object} updates - Fields to update
     * @returns {Promise<Form>}
     */
    /**
     * Delete form by UUID (internal use)
     * @param {string} uuid - UUID only
     * @returns {Promise<Form>}
     */
    static async deleteById(uuid) {
        const pool = getPool();

        // First verify the form exists
        const form = await Form.findById(uuid);

        try {
            await pool.query('DELETE FROM forms WHERE id = $1', [uuid]);
            return form;
        } catch (error) {
            throw new DatabaseError('Failed to delete form', error);
        }
    }

    static async count({ isActive = null } = {}) {
        const pool = getPool();
        let query = 'SELECT COUNT(*) as count FROM forms';
        const params = [];

        if (isActive !== null) {
            query += ' WHERE is_active = $1';
            params.push(isActive);
        }

        const result = await pool.query(query, params);
        return parseInt(result.rows[0].count, 10);
    }

    /**
     * Batch create forms
     * @param {Array} formsData - Array of form data objects
     * @returns {Promise<Array<Form>>}
     */
    static async createMany(formsData) {
        if (!Array.isArray(formsData) || formsData.length === 0) {
            return [];
        }

        const pool = getPool();
        const client = await pool.connect();

        try {
            await client.query('BEGIN');

            // Generate all SIDs first
            const sids = [];
            for (let i = 0; i < formsData.length; i++) {
                const counter = await getNextSIDCounter('form', client);
                const sid = generateSID('form', counter);
                sids.push(sid);
            }

            // Build bulk insert query
            const values = [];
            const placeholders = [];
            let paramIndex = 1;

            formsData.forEach((formData, index) => {
                const sid = sids[index];
                const enhancedMetadata = Form.buildEnhancedMetadata(formData.questions, formData.metadata);
                placeholders.push(
                    `($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3}, $${paramIndex + 4}, $${paramIndex + 5})`
                );
                values.push(
                    sid,
                    formData.title,
                    formData.description || '',
                    JSON.stringify(formData.questions),
                    JSON.stringify(enhancedMetadata),
                    true
                );
                paramIndex += 6;
            });

            const query = `
        INSERT INTO forms (sid, title, description, questions, metadata, is_active)
        VALUES ${placeholders.join(', ')}
        RETURNING *
      `;

            const result = await client.query(query, values);
            await client.query('COMMIT');

            return result.rows.map(row => Form.fromRow(row));
        } catch (error) {
            await client.query('ROLLBACK');
            throw new DatabaseError('Failed to create forms in bulk', error);
        } finally {
            client.release();
        }
    }

    /**
     * Find forms by multiple UUIDs (internal use)
     * @param {Array<string>} uuids - Array of UUIDs
     * @returns {Promise<Array<Form>>}
     */
    static async findByIds(uuids) {
        if (!Array.isArray(uuids) || uuids.length === 0) {
            return [];
        }

        const pool = getPool();

        const result = await pool.query(
            'SELECT * FROM forms WHERE id = ANY($1)',
            [uuids]
        );

        return result.rows.map(row => Form.fromRow(row));
    }

    /**
     * Find forms by multiple SIDs (user-facing)
     * @param {Array<string>} sids - Array of SIDs
     * @returns {Promise<Array<Form>>}
     */
}
