/**
 * Question Model - v4.0.0
 * 
 * This model uses the dual-ID system:
 * - id (UUID): Internal primary key for all database operations
 * - sid (VARCHAR): Human-readable ID (Q-001) for display only
 */

import { getPool } from '../config/database.js';
import { generateSID, getNextSIDCounter } from '../utils/idResolver.js';
import { DatabaseError, NotFoundError } from '../utils/errors.js';

export class Question {
    constructor(data) {
        this.id = data.id;                                    // UUID (primary key)
        this.sid = data.sid;                                  // Human-readable (Q-001)
        this.questionText = data.questionText ?? data.question_text;
        this.questionType = data.questionType ?? data.question_type;
        this.options = data.options;
        this.validationRules = data.validationRules ?? data.validation_rules;
        this.metadata = data.metadata;
        this.isActive = data.isActive ?? data.is_active;
        this.createdAt = data.createdAt ?? data.created_at;
        this.updatedAt = data.updatedAt ?? data.updated_at;
    }

    toJSON() {
        return {
            id: this.id,           // UUID for API operations
            sid: this.sid,         // Human-readable for display
            questionText: this.questionText,
            questionType: this.questionType,
            options: this.options,
            validationRules: this.validationRules,
            metadata: this.metadata,
            isActive: this.isActive,
            createdAt: this.createdAt,
            updatedAt: this.updatedAt,
        };
    }

    static fromRow(row) {
        if (!row) return null;
        return new Question({
            id: row.id,
            sid: row.sid,
            questionText: row.question_text,
            questionType: row.question_type,
            options: row.options,
            validationRules: row.validation_rules,
            metadata: row.metadata,
            isActive: row.is_active,
            createdAt: row.created_at,
            updatedAt: row.updated_at,
        });
    }

    static async create({ questionText, questionType, options = null, validationRules = null, metadata = {} }) {
        const pool = getPool();

        // Generate SID (human-readable ID)
        const counter = await getNextSIDCounter('question');
        const sid = generateSID('question', counter);

        try {
            // UUID is generated by database (DEFAULT gen_random_uuid())
            const result = await pool.query(
                `INSERT INTO question_bank (sid, question_text, question_type, options, validation_rules, metadata, is_active)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         RETURNING *`,
                [
                    sid,
                    questionText,
                    questionType,
                    options ? JSON.stringify(options) : null,
                    validationRules ? JSON.stringify(validationRules) : null,
                    JSON.stringify(metadata),
                    true,
                ]
            );

            return Question.fromRow(result.rows[0]);
        } catch (error) {
            throw new DatabaseError('Failed to create question', error);
        }
    }

    /**
     * Find question by UUID (internal use)
     * @param {string} uuid - UUID only
     * @returns {Promise<Question>}
     */
    static async findById(uuid) {
        const pool = getPool();

        const result = await pool.query('SELECT * FROM question_bank WHERE id = $1', [uuid]);

        if (result.rows.length === 0) {
            throw new NotFoundError('Question', uuid);
        }

        return Question.fromRow(result.rows[0]);
    }

    /**
     * Find question by SID (user-facing)
     * @param {string} sid - SID only (e.g., 'Q-001')
     * @returns {Promise<Question>}
     */
    static async findAll({ questionType = null, isActive = null, limit = 100, offset = 0 } = {}) {
        const pool = getPool();
        const whereClauses = [];
        const params = [];
        let paramIndex = 1;

        if (questionType) {
            whereClauses.push(`question_type = $${paramIndex++}`);
            params.push(questionType);
        }

        if (isActive !== null) {
            whereClauses.push(`is_active = $${paramIndex++}`);
            params.push(isActive);
        }

        let query = 'SELECT * FROM question_bank';
        if (whereClauses.length > 0) {
            query += ' WHERE ' + whereClauses.join(' AND ');
        }

        query += ` ORDER BY created_at DESC LIMIT $${paramIndex++} OFFSET $${paramIndex}`;
        params.push(limit, offset);

        const result = await pool.query(query, params);
        return result.rows.map((row) => Question.fromRow(row));
    }

    /**
     * Find questions by multiple UUIDs (internal use)
     * @param {Array<string>} uuids - Array of UUIDs
     * @returns {Promise<Array<Question>>}
     */
    static async findByIds(uuids) {
        if (!uuids || uuids.length === 0) {
            return [];
        }

        const pool = getPool();

        const result = await pool.query(
            'SELECT * FROM question_bank WHERE id = ANY($1)',
            [uuids]
        );

        return result.rows.map((row) => Question.fromRow(row));
    }

    /**
     * Find questions by multiple SIDs (user-facing)
     * @param {Array<string>} sids - Array of SIDs
     * @returns {Promise<Array<Question>>}
     */
    /**
     * Update question by UUID (internal use)
     * @param {string} uuid - UUID only
     * @param {object} updates - Fields to update
     * @returns {Promise<Question>}
     */
    static async updateById(uuid, updates) {
        const pool = getPool();
        const client = await pool.connect();

        try {
            await client.query('BEGIN');

            const question = await Question.findById(uuid);

            const setClauses = [];
            const values = [];
            let paramIndex = 1;

            if (updates.questionText !== undefined) {
                setClauses.push(`question_text = $${paramIndex++}`);
                values.push(updates.questionText);
            }

            if (updates.questionType !== undefined) {
                setClauses.push(`question_type = $${paramIndex++}`);
                values.push(updates.questionType);
            }

            if (updates.options !== undefined) {
                setClauses.push(`options = $${paramIndex++}`);
                values.push(updates.options ? JSON.stringify(updates.options) : null);
            }

            if (updates.validationRules !== undefined) {
                setClauses.push(`validation_rules = $${paramIndex++}`);
                values.push(updates.validationRules ? JSON.stringify(updates.validationRules) : null);
            }

            if (updates.metadata !== undefined) {
                setClauses.push(`metadata = $${paramIndex++}`);
                values.push(JSON.stringify(updates.metadata));
            }

            if (updates.isActive !== undefined) {
                setClauses.push(`is_active = $${paramIndex++}`);
                values.push(updates.isActive);
            }

            if (setClauses.length === 0) {
                await client.query('COMMIT');
                return question;
            }

            values.push(uuid);
            const query = `UPDATE question_bank SET ${setClauses.join(', ')} WHERE id = $${paramIndex} RETURNING *`;

            const result = await client.query(query, values);
            await client.query('COMMIT');

            return Question.fromRow(result.rows[0]);
        } catch (error) {
            await client.query('ROLLBACK');
            throw new DatabaseError('Failed to update question', error);
        } finally {
            client.release();
        }
    }

    /**
     * Update question by SID (user-facing)
     * @param {string} sid - SID only (e.g., 'Q-001')
     * @param {object} updates - Fields to update
     * @returns {Promise<Question>}
     */
    /**
     * Delete question by UUID (internal use)
     * @param {string} uuid - UUID only
     * @returns {Promise<Question>}
     */
    static async deleteById(uuid) {
        const pool = getPool();
        const client = await pool.connect();

        try {
            await client.query('BEGIN');

            const question = await Question.findById(uuid);

            await client.query('DELETE FROM question_bank WHERE id = $1', [uuid]);

            await client.query('COMMIT');

            return question;
        } catch (error) {
            await client.query('ROLLBACK');
            throw new DatabaseError('Failed to delete question', error);
        } finally {
            client.release();
        }
    }

    static async count({ questionType = null, isActive = null } = {}) {
        const pool = getPool();
        const whereClauses = [];
        const params = [];
        let paramIndex = 1;

        if (questionType) {
            whereClauses.push(`question_type = $${paramIndex++}`);
            params.push(questionType);
        }

        if (isActive !== null) {
            whereClauses.push(`is_active = $${paramIndex++}`);
            params.push(isActive);
        }

        let query = 'SELECT COUNT(*) as count FROM question_bank';
        if (whereClauses.length > 0) {
            query += ' WHERE ' + whereClauses.join(' AND ');
        }

        const result = await pool.query(query, params);
        return parseInt(result.rows[0].count, 10);
    }

    /**
     * Batch create questions
     * @param {Array} questionsData - Array of question data objects
     * @returns {Promise<Array<Question>>}
     */
    static async createMany(questionsData) {
        if (!Array.isArray(questionsData) || questionsData.length === 0) {
            return [];
        }

        const pool = getPool();
        const client = await pool.connect();

        try {
            await client.query('BEGIN');

            // Generate all SIDs first
            const sids = [];
            for (let i = 0; i < questionsData.length; i++) {
                const counter = await getNextSIDCounter('question', client);
                const sid = generateSID('question', counter);
                sids.push(sid);
            }

            // Build bulk insert query
            const values = [];
            const placeholders = [];
            let paramIndex = 1;

            questionsData.forEach((questionData, index) => {
                const sid = sids[index];
                placeholders.push(
                    `($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3}, $${paramIndex + 4}, $${paramIndex + 5}, $${paramIndex + 6})`
                );
                values.push(
                    sid,
                    questionData.questionText,
                    questionData.questionType,
                    questionData.options ? JSON.stringify(questionData.options) : null,
                    questionData.validationRules ? JSON.stringify(questionData.validationRules) : null,
                    JSON.stringify(questionData.metadata || {}),
                    true
                );
                paramIndex += 7;
            });

            const query = `
        INSERT INTO question_bank (sid, question_text, question_type, options, validation_rules, metadata, is_active)
        VALUES ${placeholders.join(', ')}
        RETURNING *
      `;

            const result = await client.query(query, values);
            await client.query('COMMIT');

            return result.rows.map(row => Question.fromRow(row));
        } catch (error) {
            await client.query('ROLLBACK');
            throw new DatabaseError('Failed to create questions in bulk', error);
        } finally {
            client.release();
        }
    }

    /**
     * Batch delete questions by UUIDs (internal use)
     * @param {Array<string>} uuids - Array of UUIDs
     * @returns {Promise<Array<Question>>}
     */
    static async deleteMany(uuids) {
        if (!Array.isArray(uuids) || uuids.length === 0) {
            return [];
        }

        const pool = getPool();
        const client = await pool.connect();

        try {
            await client.query('BEGIN');

            // Fetch questions before deletion for return value
            const selectResult = await client.query(
                'SELECT * FROM question_bank WHERE id = ANY($1)',
                [uuids]
            );
            const questions = selectResult.rows.map(row => Question.fromRow(row));

            // Bulk delete
            await client.query(
                'DELETE FROM question_bank WHERE id = ANY($1)',
                [uuids]
            );

            await client.query('COMMIT');
            return questions;
        } catch (error) {
            await client.query('ROLLBACK');
            throw new DatabaseError('Failed to delete questions in bulk', error);
        } finally {
            client.release();
        }
    }
}
