/**
 * Submission Model - v4.0.0
 * 
 * This model uses the dual-ID system:
 * - id (UUID): Internal primary key for all database operations
 * - sid (VARCHAR): Human-readable ID (SUB-001) for display only
 * - formId (UUID): Foreign key to forms table (always UUID)
 * - formSid (VARCHAR): Denormalized form SID stored for reporting
 */

import { getPool } from '../config/database.js';
import { generateSID, getNextSIDCounter } from '../utils/idResolver.js';
import { DatabaseError, NotFoundError } from '../utils/errors.js';
import { Form } from './Form.js';

export class Submission {
  constructor(data) {
    this.id = data.id;                                    // UUID (primary key)
    this.sid = data.sid;                                  // Human-readable (SUB-001)
    this.formId = data.formId ?? data.form_id;           // UUID (foreign key)
    this.formSid = data.formSid ?? data.form_sid;        // Human-readable form ID
    this.submissionData = data.submissionData ?? data.submission_data;
    this.metadata = data.metadata;
    this.submittedAt = data.submittedAt ?? data.submitted_at;
    // Phase 3: submission targeting fields
    this.targetUnitId = data.targetUnitId ?? data.target_unit_id ?? null;
    this.submitterUserId = data.submitterUserId ?? data.submitter_user_id ?? null;
  }

  toJSON() {
    return {
      id: this.id,           // UUID for API operations
      sid: this.sid,         // Human-readable for display
      formId: this.formId,   // UUID (foreign key)
      formSid: this.formSid, // Human-readable form ID
      submissionData: this.submissionData,
      metadata: this.metadata,
      submittedAt: this.submittedAt,
      // Phase 3: submission targeting fields
      targetUnitId: this.targetUnitId,
      submitterUserId: this.submitterUserId,
    };
  }

  static fromRow(row) {
    if (!row) return null;
    return new Submission({
      id: row.id,
      sid: row.sid,
      formId: row.form_id,
      formSid: row.form_sid,
      submissionData: row.submission_data,
      metadata: row.metadata,
      submittedAt: row.submitted_at,
      // Phase 3: map snake_case DB columns to camelCase fields
      target_unit_id: row.target_unit_id,
      submitter_user_id: row.submitter_user_id,
    });
  }

  /**
   * Create submission (accepts formId UUID) with retry logic for SID conflicts
   * @param {object} params
   * @param {string} params.formId - Form UUID
   * @param {object} params.submissionData - Submission data
   * @param {object} params.metadata - Metadata
   * @returns {Promise<Submission>}
   */
  static async create({ formId, submissionData, metadata = {}, targetUnitId = null, submitterUserId = null }) {
    const pool = getPool();

    // Get form to populate form_sid
    const form = await Form.findById(formId);
    const formSid = form.sid;  // Get SID for denormalized column

    // Retry logic for concurrent SID conflicts
    const maxRetries = 10;  // Increased from 5 for high concurrency
    let lastError;

    for (let attempt = 0; attempt < maxRetries; attempt++) {
      try {
        // Generate SID (human-readable ID)
        const counter = await getNextSIDCounter('submission');
        const sid = generateSID('submission', counter);

        // UUID is generated by database (DEFAULT gen_random_uuid())
        // Store both form_id (UUID) and form_sid (VARCHAR)
        const result = await pool.query(
          `INSERT INTO submissions (sid, form_id, form_sid, submission_data, metadata, target_unit_id, submitter_user_id)
           VALUES ($1, $2, $3, $4, $5, $6, $7)
           RETURNING *`,
          [sid, formId, formSid, JSON.stringify(submissionData), JSON.stringify(metadata), targetUnitId, submitterUserId]
        );

        return Submission.fromRow(result.rows[0]);
      } catch (error) {
        lastError = error;

        // Check if it's a duplicate SID error (PostgreSQL error code 23505)
        if (error.code === '23505' && error.constraint === 'submissions_sid_unique') {
          // Log retry attempt in non-production
          if (process.env.NODE_ENV !== 'production') {
            console.warn(`SID conflict on attempt ${attempt + 1}/${maxRetries}, retrying...`);
          }

          // Add small random delay to reduce collision probability (10-50ms)
          await new Promise(resolve => setTimeout(resolve, 10 + Math.random() * 40));
          continue;
        }

        // For other errors, throw immediately
        if (process.env.NODE_ENV !== 'production') {
          console.error('Submission creation error:', error.message, error.code);
        }
        throw new DatabaseError('Failed to create submission', error);
      }
    }

    // If we exhausted all retries, throw the last error
    throw new DatabaseError(`Failed to create submission after ${maxRetries} attempts (SID conflicts)`, lastError);
  }

  /**
   * Find submission by UUID (internal use)
   * @param {string} uuid - UUID only
   * @returns {Promise<Submission>}
   */
  static async findById(uuid) {
    const pool = getPool();

    const result = await pool.query('SELECT * FROM submissions WHERE id = $1', [uuid]);

    if (result.rows.length === 0) {
      throw new NotFoundError('Submission', uuid);
    }

    return Submission.fromRow(result.rows[0]);
  }

  /**
   * Find submissions by form UUID (internal use)
   * @param {string} formUuid - Form UUID
   * @param {object} options - Pagination options
   * @returns {Promise<Array<Submission>>}
   */
  static async findByFormId(formUuid, { limit = 100, offset = 0 } = {}) {
    const pool = getPool();

    const result = await pool.query(
      'SELECT * FROM submissions WHERE form_id = $1 ORDER BY submitted_at DESC LIMIT $2 OFFSET $3',
      [formUuid, limit, offset]
    );

    return result.rows.map((row) => Submission.fromRow(row));
  }

  static async findAll({ limit = 100, offset = 0 } = {}) {
    const pool = getPool();
    const result = await pool.query(
      'SELECT * FROM submissions ORDER BY submitted_at DESC LIMIT $1 OFFSET $2',
      [limit, offset]
    );

    return result.rows.map((row) => Submission.fromRow(row));
  }

  /**
   * Update submission by UUID (internal use)
   * @param {string} uuid - UUID only
   * @param {object} updates - Fields to update
   * @returns {Promise<Submission>}
   */
  static async updateById(uuid, updates) {
    const pool = getPool();
    const client = await pool.connect();

    try {
      await client.query('BEGIN');

      const submission = await Submission.findById(uuid);

      const setClauses = [];
      const values = [];
      let paramIndex = 1;

      if (updates.submissionData !== undefined) {
        setClauses.push(`submission_data = $${paramIndex++}`);
        values.push(JSON.stringify(updates.submissionData));
      }

      if (updates.metadata !== undefined) {
        setClauses.push(`metadata = $${paramIndex++}`);
        values.push(JSON.stringify(updates.metadata));
      }

      if (setClauses.length === 0) {
        await client.query('COMMIT');
        return submission;
      }

      values.push(uuid);
      const query = `UPDATE submissions SET ${setClauses.join(', ')} WHERE id = $${paramIndex} RETURNING *`;

      const result = await client.query(query, values);
      await client.query('COMMIT');

      return Submission.fromRow(result.rows[0]);
    } catch (error) {
      await client.query('ROLLBACK');
      throw new DatabaseError('Failed to update submission', error);
    } finally {
      client.release();
    }
  }

  /**
   * Update submission by SID (user-facing)
   * @param {string} sid - SID only (e.g., 'SUB-001')
   * @param {object} updates - Fields to update
   * @returns {Promise<Submission>}
   */
  /**
   * Delete submission by UUID (internal use)
   * @param {string} uuid - UUID only
   * @returns {Promise<Submission>}
   */
  static async deleteById(uuid) {
    const pool = getPool();
    const client = await pool.connect();

    try {
      await client.query('BEGIN');

      const submission = await Submission.findById(uuid);

      await client.query('DELETE FROM submissions WHERE id = $1', [uuid]);

      await client.query('COMMIT');

      return submission;
    } catch (error) {
      await client.query('ROLLBACK');
      throw new DatabaseError('Failed to delete submission', error);
    } finally {
      client.release();
    }
  }

  /**
   * Count submissions
   * @param {object} options
   * @param {string} options.formId - Form UUID (optional)
   * @returns {Promise<number>}
   */
  static async count({ formId = null } = {}) {
    const pool = getPool();
    let query = 'SELECT COUNT(*) as count FROM submissions';
    const params = [];

    if (formId) {
      query += ' WHERE form_id = $1';
      params.push(formId);
    }

    const result = await pool.query(query, params);
    return parseInt(result.rows[0].count, 10);
  }

  /**
   * Batch create submissions
   * @param {Array} submissionsData - Array of submission data objects with formId (UUID)
   * @returns {Promise<Array<Submission>>}
   */
  static async createMany(submissionsData) {
    if (!Array.isArray(submissionsData) || submissionsData.length === 0) {
      return [];
    }

    const pool = getPool();
    const client = await pool.connect();

    try {
      await client.query('BEGIN');

      // Get unique formIds (UUIDs) and fetch forms
      const uniqueFormIds = [...new Set(submissionsData.map(s => s.formId))];
      const forms = await Promise.all(
        uniqueFormIds.map(id => Form.findById(id))
      );

      // Create mapping of formId (UUID) to formSid
      const formIdToSidMap = new Map();
      forms.forEach(form => {
        formIdToSidMap.set(form.id, form.sid);
      });

      // Generate all SIDs first
      const sids = [];
      for (let i = 0; i < submissionsData.length; i++) {
        const counter = await getNextSIDCounter('submission', client);
        const sid = generateSID('submission', counter);
        sids.push(sid);
      }

      // Build bulk insert query
      const values = [];
      const placeholders = [];
      let paramIndex = 1;

      submissionsData.forEach((submissionData, index) => {
        const sid = sids[index];
        const formId = submissionData.formId;
        const formSid = formIdToSidMap.get(formId);

        if (!formSid) {
          throw new NotFoundError('Form', formId);
        }

        placeholders.push(
          `($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3}, $${paramIndex + 4})`
        );
        values.push(
          sid,
          formId,
          formSid,
          JSON.stringify(submissionData.submissionData),
          JSON.stringify(submissionData.metadata || {})
        );
        paramIndex += 5;
      });

      const query = `
        INSERT INTO submissions (sid, form_id, form_sid, submission_data, metadata)
        VALUES ${placeholders.join(', ')}
        RETURNING *
      `;

      const result = await client.query(query, values);
      await client.query('COMMIT');

      return result.rows.map(row => Submission.fromRow(row));
    } catch (error) {
      await client.query('ROLLBACK');
      if (error instanceof NotFoundError) {
        throw error;
      }
      throw new DatabaseError('Failed to create submissions in bulk', error);
    } finally {
      client.release();
    }
  }

  /**
   * Batch delete submissions by UUIDs (internal use)
   * @param {Array<string>} uuids - Array of UUIDs
   * @returns {Promise<Array<Submission>>}
   */
  static async deleteMany(uuids) {
    if (!Array.isArray(uuids) || uuids.length === 0) {
      return [];
    }

    const pool = getPool();
    const client = await pool.connect();

    try {
      await client.query('BEGIN');

      // Fetch submissions before deletion for return value
      const selectResult = await client.query(
        'SELECT * FROM submissions WHERE id = ANY($1)',
        [uuids]
      );
      const submissions = selectResult.rows.map(row => Submission.fromRow(row));

      // Bulk delete
      await client.query(
        'DELETE FROM submissions WHERE id = ANY($1)',
        [uuids]
      );

      await client.query('COMMIT');
      return submissions;
    } catch (error) {
      await client.query('ROLLBACK');
      throw new DatabaseError('Failed to delete submissions in bulk', error);
    } finally {
      client.release();
    }
  }
}
